#! /bin/bash

GOOS=linux GOARCH=amd64 go build -ldflags="-s -w"
upx status

scp -i ~/Atlas.pem status ec2-user@status.bign8.info:/usr/sbin/status-server

ssh -T -i ~/Atlas.pem ec2-user@status.bign8.info <<EOF
  sudo kill -9 \$(sudo lsof -ti tcp:8081)
  sudo nohup status-server > status.out 2> status.err < /dev/null &
  echo "Deploy Complete"
EOF
