name: status
authors:
  - Nate Woods <me@bign8.info>
homepage: http://status.bign8.info/
description: Matrics Environment Monitor
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  json_annotation: "^3.0.0"
dev_dependencies:
  build_runner: ">=1.6.2 <2.0.0"
  json_serializable: "^3.0.0"
  build_web_compilers: ">=2.12.0 <3.0.0"
