name: status
authors:
  - Nate Woods <me@bign8.info>
homepage: http://status.bign8.info/
description: Matrics Environment Monitor
environment:
  sdk: ">=2.10.0 <3.0.0"
#dependencies:
#  json_object: any
#  browser: any
#  dart_to_js_script_rewriter: any
#transformers:
#  - $dart2js:
#      commandLineOptions:
#        - --enable-experimental-mirrors
#  - dart_to_js_script_rewriter
dev_dependencies:
  build_runner: ">=1.6.2 <2.0.0"
  build_web_compilers: ">=2.12.0 <3.0.0"
